### ISSUE TITLE
Separate output from each sample pair into its own subfolder labeled by the `pairId`

### ISSUE THREAD

**Issue by soccin** [mskcc/loki#2]
### Description of feature

The current Loki output puts all samples from the input sample file into one directory. It would be better at this stage to split the output folder into subfolders labeled by `pairId`.  So
```
$OUTPUT_ROOT/facets/pair_1
$OUTPUT_ROOT/facets/pair_2
...
```

**Comment by nikhil** [comment]
This feature has been added through #8
