### ISSUE TITLE
Consistent convention for naming Facet output files

### ISSUE THREAD

**Issue by soccin** [mskcc/loki#3]
### Description of feature

Currently the files for a given sample pair are labeled:
```
pair_24.qc.txt
pair_24.txt
pair_24.arm_level.txt
pair_24.gene_level.txt
pair_24_hisens.png
pair_24_hisens.rds
pair_24_hisens.seg
pair_24_purity.png
pair_24_purity.rds
pair_24_purity.seg
```

Let us make this consistent to either:
```
${pairId}.suffix.extension
```
so
```
pair_24.qc.txt
pair_24.summary.txt
pair_24.arm_level.txt
pair_24.gene_level.txt
pair_24.hisens.png
pair_24.hisens.rds
pair_24.hisens.seg
pair_24.purity.png
pair_24.purity.rds
pair_24.purity.seg
```

Or some other consistent scheme. In fact we can thinking of making a rule that `pairId` can not have (`.`)  to make this very easy to parse for the downstream users

**Comment by nikhil** [comment]
This feature has been added through #8
